# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift


use_frameworks!



target 'RaptorFish' do
pod "AFNetworking"
pod “Parse”
pod “Bolts”
end

target 'RaptorFishTests' do

end

target 'RaptorFishUITests' do

end
